server:
  port: 8082

spring:
  cloud:
    stream:
      function:
        definition: poloConsumer
      bindings:
        poloConsumer-in-0:
          destination: marcoPolo
      rabbit:
        bindings:
          poloConsumer-in-0:
            consumer:
              ttl: 120000